### ISSUE TITLE
Missing dll file in nuget package "Cake.XdtTransform.dll"

### ISSUE THREAD

**Issue by robgha01** [nengberg/cake-envxmltransform#1]
I added the #addin "Cake.EnvXmlTransform"
however when i run ConfigTransform.ApplyTransformations(path, configuration);
i get the error: 

> Error: System.IO.FileNotFoundException: Can not load file or assembly Cake.XdtTransform, Version = 0.9.11.0, Culture = neutral, PublicKeyToken = null or one of its dependencies. The file can not be found.
> Filename: Cake.XdtTransform, Version = 0.9.11.0, Culture = neutral, PublicKeyToken = null
>     at Cake.EnvXmlTransform.EnvironmentalXmlTransformRunner.TransformConfigurations (Dictionary`2 organizedConfigFiles)...

![image](https://cloud.githubusercontent.com/assets/362726/21011837/6ddc8df2-bd53-11e6-8b9d-996e96922529.png)

the version in properties of the dll do not match the version expected by the console runner.

Cake version im using is 0.14.0.0 in expremental mode.

**Comment by robgha01** [comment]
@nengberg ether include it or update the documentation that one need to add #addin for the missing dll file.

**Comment by nengberg** [comment]
Hi @robgha01 and thanks for trying out my plugin. 

It seems that you are the first one using! I haven't received any complaints yet! 😄  I've published a new release now and it should be all in place. Please get back to me if I have missed anything!

Regards
Niklas

**Comment by nengberg** [comment]
Do you still experience any problems @robgha01 or can I close this one?
