### ISSUE TITLE
Upgrade with last version of cake core

### ISSUE THREAD

**Issue by binard** [nengberg/cake-envxmltransform#2]
Could you update your package to set it compatible with the last version of Cake.Core ?

Thanks !

Error: The assembly 'Cake.EnvXmlTransform, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.13.0). This assembly need to reference at least Cake.Core version 0.16.0. Another option is to downgrade Cake to an earlier version.

**Comment by nengberg** [comment]
Hello @binard. Thanks for considering my plugin! I will look into getting that fixed as soon as possible!

**Comment by nengberg** [comment]
@binard I have published an new package (0.3.0) to Nuget now. That package has not been indexed yet, but soon it will be available for you. Lets me know if you still encounter any issues.

Regards
Niklas

**Comment by binard** [comment]
Thank you very much for your quick response. The package is available but I'have an other error about assembly 'Cake.XdtTransform'

Error: The assembly 'Cake.XdtTransform, Version=0.9.11.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.11.0). This assembly need to reference at least Cake.Core version 0.16.0. Another option is to downgrade Cake to an earlier version.

**Comment by nengberg** [comment]
Bah...Didn't see that one coming! Thanks for getting back to me! I have pushed a 0.3.1 so lets pray that it works @binard

**Comment by binard** [comment]
@nengberg It works ! Good job, thanks
